version: '3.8'

services:
  web:
    build: .
    ports:
      - "2106:2106"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: